"""add media and persistent jobs

Revision ID: 3fed32f2a46b
Revises: 4010dfc6503c
Create Date: 2026-07-19 17:32:47.677204
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3fed32f2a46b"
down_revision: str | None = "4010dfc6503c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("job_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("target_version", sa.Integer(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_by", sa.String(length=128), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_jobs_attempts_nonnegative"),
        sa.CheckConstraint("max_attempts >= 1", name="ck_jobs_max_attempts_positive"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_jobs_claim", ["status", "available_at", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            "uq_jobs_active_aggregate",
            ["job_type", "aggregate_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('pending', 'running')"),
        )

    op.create_table(
        "media",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=32), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("relative_path", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("relative_path"),
        sa.UniqueConstraint("sha256"),
    )
    op.create_table(
        "note_media",
        sa.Column("note_id", sa.String(length=36), nullable=False),
        sa.Column("usage", sa.String(length=64), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("note_id", "usage"),
    )
    with op.batch_alter_table("note_media", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_note_media_media_id"), ["media_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("note_media", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_note_media_media_id"))

    op.drop_table("note_media")
    op.drop_table("media")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_jobs_active_aggregate", sqlite_where=sa.text("status IN ('pending', 'running')")
        )
        batch_op.drop_index("ix_jobs_claim")

    op.drop_table("jobs")
    # ### end Alembic commands ###
