"""add dictionary cache foundation

Revision ID: c2c932fd1820
Revises: 3fed32f2a46b
Create Date: 2026-07-19 17:56:49.390023
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c2c932fd1820"
down_revision: str | None = "3fed32f2a46b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dictionary_cache_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("provider_dataset", sa.String(length=128), nullable=True),
        sa.Column("provider_config_version", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("normalized_query", sa.JSON(), nullable=False),
        sa.Column("response_payload", sa.JSON(), nullable=False),
        sa.Column("response_hash", sa.String(length=64), nullable=False),
        sa.Column("source_entry_ids", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "request_key", name="uq_dictionary_cache_provider_key"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("dictionary_cache_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_artifacts_dictionary_cache_id"), ["dictionary_cache_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_artifacts_dictionary_cache_id",
            "dictionary_cache_entries",
            ["dictionary_cache_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_artifacts_dictionary_cache_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_artifacts_dictionary_cache_id"))
        batch_op.drop_column("dictionary_cache_id")

    op.drop_table("dictionary_cache_entries")
    # ### end Alembic commands ###
