"""add generation provider trace

Revision ID: d033c4ab7251
Revises: c2c932fd1820
Create Date: 2026-07-19 18:06:46.656776
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d033c4ab7251"
down_revision: str | None = "c2c932fd1820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("provider_response_id", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_column("provider_response_id")

    # ### end Alembic commands ###
