"""add speech cache and draft confirmation

Revision ID: dfd8206eedfc
Revises: d033c4ab7251
Create Date: 2026-07-19 18:27:53.613383
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dfd8206eedfc"
down_revision: str | None = "d033c4ab7251"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "speech_cache_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=128), nullable=False),
        sa.Column("config_version", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("locale", sa.String(length=32), nullable=False),
        sa.Column("voice", sa.String(length=128), nullable=False),
        sa.Column("ssml", sa.Text(), nullable=False),
        sa.Column("output_format", sa.String(length=128), nullable=False),
        sa.Column("media_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["media_id"], ["media.id"], name="fk_speech_cache_media_id", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cache_key"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("media_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_artifacts_media_id"), ["media_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_artifacts_media_id", "media", ["media_id"], ["id"], ondelete="SET NULL"
        )

    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.String(length=32), server_default="editable", nullable=False)
        )
        batch_op.add_column(
            sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False)
        )
        batch_op.add_column(sa.Column("confirmed_note_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_drafts_confirmed_note_id",
            "notes",
            ["confirmed_note_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("drafts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_drafts_confirmed_note_id", type_="foreignkey")
        batch_op.drop_column("confirmed_note_id")
        batch_op.drop_column("version")
        batch_op.drop_column("status")

    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_artifacts_media_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_artifacts_media_id"))
        batch_op.drop_column("media_id")

    op.drop_table("speech_cache_entries")
    # ### end Alembic commands ###
