from typing import Any, Protocol


class AnkiGateway(Protocol):
    async def deck_names(self) -> list[str]: ...

    async def create_deck(self, name: str) -> int: ...

    async def model_names(self) -> list[str]: ...

    async def model_field_names(self, name: str) -> list[str]: ...

    async def create_model(
        self, *, name: str, fields: list[str], css: str, templates: list[dict[str, str]]
    ) -> object: ...

    async def store_media(self, *, filename: str, content: bytes) -> str: ...

    async def find_notes(self, query: str) -> list[int]: ...

    async def add_note(
        self, *, deck: str, model: str, fields: dict[str, str], tags: list[str]
    ) -> int: ...

    async def update_note(
        self, note_id: int, *, fields: dict[str, str], tags: list[str]
    ) -> None: ...

    async def notes_info(self, note_ids: list[int]) -> list[dict[str, Any]]: ...

    async def delete_notes(self, note_ids: list[int]) -> None: ...
